image: golang:1.16.2

stages:
  - transporter_build
  - transporter_docker_build
  - transporter_deploy

before_script:
  - export GOPATH=$GOPATH:/usr/local/${CI_PROJECT_NAME}
  - export VERSION=`echo ${CI_COMMIT_TAG} | awk -F"_" '{print $1}'`
  - export GO111MODULE=on
  - export GOPROXY=https://goproxy.cn

cache:
  paths:
    - /go/pkg

# transporter 编译
transporter_build:
  stage: transporter_build
  only:
    - master
    - dev-transporter
  script:
    - echo '下载依赖'
    - pwd
    - ls
    - cd service/transporter
    - go mod tidy
    - echo '开始构建'
    - make build
    - echo '构建完成'
  tags:
    - docker
  artifacts:
    paths:
      - service/transporter/build/bin/transporter
    when: always
    expire_in: 4 weeks

transporter_docker_build:
  stage: transporter_docker_build
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  variables: 
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  dependencies:
    - transporter_build
  only:
    - master
    - dev-transporter
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN $CI_REGISTRY
  script:
    - echo '构建 transporter docker 镜像'
    - cd service/transporter
    - docker build -t transporter:v1-dev .
    - docker tag transporter:v1-dev harbor.sumblog.cn/pub/transporter:v1-dev
    - docker push harbor.sumblog.cn/pub/transporter:v1-dev

# 登录项目部署服务器，移除旧版本项目文件，最后将打包好的文件拷贝过去
transporter_deploy_job:
  stage: transporter_deploy
  image: ubuntu:latest
  only:
    - master
    - dev-transporter
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - source .${CI_COMMIT_REF_NAME}.env
  script:
    - cd service/transporter
    - echo '登录项目部署服务器，删除旧 docker，拉取新镜像'
    - ssh zjh@$DEV_SERVER "uname -a"
  tags:
    - docker
