version: "3"

services:
    portal:
        depends_on: 
            - httpserver
        image: jcs-portal
        volumes: 
            - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"

    httpserver:
        depends_on: 
            - scheduler
            - transporter
        image: httpserver
        volumes: 
            - ./configs/httpserver.properties:/home/jcspan/httpserver.properties:ro

    scheduler:
        image: scheduler
        command: ./scheduler -env=prod -cid=aliyun-hangzhou
        ports:
            - "8082:8082"

    transporter:
        image: transporter
        volumes: 
            - ./configs/transporter_config.json:/home/jcspan/config/transporter_config.json:ro
        command: ./transporter
