version: "3"

services:
    portal:
        depends_on:
            - httpserver
        image: harbor.sumblog.cn/pub/portal:v1-dev
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "8080:80"

    httpserver:
        depends_on:
            - scheduler
            - transporter
        image: harbor.sumblog.cn/pub/httpserver:v1-dev
        volumes:
            - ./httpserver.properties:/home/jcspan/httpserver.properties:ro

    scheduler:
        depends_on:
            - mongodb
        image: harbor.sumblog.cn/pub/scheduler:v1-dev
        command: ./scheduler -env=prod -cid=<this-cloud-id> -mongo=mongodb://mongodb:27017
        ports:
            - "8082:8082"

    transporter:
        depends_on:
            - mongodb
        image: harbor.sumblog.cn/pub/transporter:v1-dev
        volumes:
            - ./transporter_config.json.docker:/home/jcspan/transporter_config.json:ro
            - transporter-data:/data:rw
        command: ./transporter
        ports:
            - "8083:8083"
            
    mongodb:
        image: mongo:4.4.5
        environment:
            MONGO_INITDB_DATABASE: prod
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
    transporter-data: