FROM node@sha256:95de040aa148ca391a29674ca99931bf486e87c33eca566c3f6af984609d1c84 as build-stage
WORKDIR /portal
COPY package*.json ./
RUN SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ npm install --registry=https://registry.npm.taobao.org
COPY ./ .
RUN npm run build

FROM nginx:1.17.10-alpine as production-stage
RUN mkdir /portal
COPY --from=build-stage /portal/dist /portal
